// Copyright (c) 2017-2018 The CDC developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or http://www.opensource.org/licenses/mit-license.php.


/* This is an autogenerated file, based on url.hpp.in
   Do not edit url.hpp directly! Edit url.hpp.in  */

#pragma once

#define CUSTOM_URL_SCHEME "cdcchain"
